/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  ChildComponent as ChildComponent
} from './components/child-component/child-component';

declare global {
  interface HTMLChildComponentElement extends ChildComponent, HTMLStencilElement {
  }
  var HTMLChildComponentElement: {
    prototype: HTMLChildComponentElement;
    new (): HTMLChildComponentElement;
  };
  interface HTMLElementTagNameMap {
    "child-component": HTMLChildComponentElement;
  }
  interface ElementTagNameMap {
    "child-component": HTMLChildComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "child-component": JSXElements.ChildComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface ChildComponentAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}


import {
  ParentComponent as ParentComponent
} from './components/parent-component/parent-component';

declare global {
  interface HTMLParentComponentElement extends ParentComponent, HTMLStencilElement {
  }
  var HTMLParentComponentElement: {
    prototype: HTMLParentComponentElement;
    new (): HTMLParentComponentElement;
  };
  interface HTMLElementTagNameMap {
    "parent-component": HTMLParentComponentElement;
  }
  interface ElementTagNameMap {
    "parent-component": HTMLParentComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "parent-component": JSXElements.ParentComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface ParentComponentAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
